service: shipstation-partnerapi-sales-demo

provider:
  name: aws
  runtime: nodejs20.x
  region: us-west-2
  stage: dev

  # Give our Lambda functions permission to talk to DynamoDB and SSM Parameter Store
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:Scan
          Resource:
            - arn:aws:dynamodb:*:*:table/shipstation-partnerapi-demo-accounts
        - Effect: Allow
          Action:
            - ssm:GetParameter
          Resource:
            - arn:aws:ssm:*:*:parameter/shipstation-demo/*

# We will define our Lambda endpoints here.
functions:
  createAccount:
    handler: handler.createAccount
    events:
      - http:
          path: api/accounts
          method: post
          cors: true

  listAccounts:
    handler: handler.listAccounts
    events:
      - http:
          path: api/accounts
          method: get
          cors: true

  directLogin:
    handler: handler.directLogin
    events:
      - http:
          path: api/direct-login
          method: post
          cors: true

  listCarriers:
    handler: handler.listCarriers
    events:
      - http:
          path: api/carriers/{accountId}
          method: get
          cors: true

  listWarehouses:
    handler: handler.listWarehouses
    events:
      - http:
          path: api/warehouses/{accountId}
          method: get
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - On-Behalf-Of

  createWarehouse:
    handler: handler.createWarehouse
    events:
      - http:
          path: api/warehouses/{accountId}
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - On-Behalf-Of
